### ISSUE TITLE
Drivers are case sensitive

### ISSUE THREAD

**Issue by yoeriboven** [SocialiteProviders/website#2]
Lately there have been a few cases like: `Driver [driver] not supported.`

Turns out, this is because the driver needs to be lowercase. Docs are showing the driver in camelcase.

This should be fixed in the docs.

---
This doesn't work.
```
return Socialite::with('Slack')->redirect();
```

This works
```
return Socialite::with('slack')->redirect();
```

**Comment by atymic** [comment]
New docs should have this fixed since we parse the actual config file to generate. Let me know if you notice any issues:
https://github.com/SocialiteProviders/Providers/pull/505
