### ISSUE TITLE
wrong composer package name in doc

### ISSUE THREAD

**Issue by angelofan** [SocialiteProviders/website#50]
- `socialiteproviders/wechatserviceaccount` does not exist, it should be `socialiteproviders/wechat-service-account`.
- `socialiteproviders/wechatweb` does not exist, it should be `socialiteproviders/wechat-web`.
- `socialiteproviders/weixinweb` does not exist, it should be `socialiteproviders/weixin-web`.

**Comment by atymic** [comment]
Feel free to PR :)
